export const MAX_TITLE_LENGTH = 50
export const MAX_SEARCH_LENGTH = 50
export const DELAY_SEARCH = 500
export const MOVIES_NAME = 'Películas'
export const SERIES_NAME = 'Series'
export const ARTISTS_NAME = 'Artistas'
export const USERS_NAME = 'Usuarios'
export const CATEGORIES = [MOVIES_NAME, SERIES_NAME, ARTISTS_NAME, USERS_NAME]
export const INITIAL_CATEGORY = 0