version: '3.8' # Specify Compose file format version
services:
   expo: # Name of the frontend service
      container_name: expo-container
      build: ./ # Specify the directory of the Dockerfile
      ports:
         - 8081:8081 # Specify port-forwarding
         - 19000:19000 
         - 19001:19001
         - 19002:19002
      volumes: # Mount host path in the container
         - ./:/usr/src/app
         - /usr/src/app/node_modules
      environment:
         - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
         - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.2