export enum LocalIcon {
    birth=require('../../assets/icons/birth.png'),
    death=require('../../assets/icons/death.png'),
    location=require('../../assets/icons/location.png'),
    instagram=require('../../assets/icons/instagram.png'),
    twitter=require('../../assets/icons/twitter.png'),
    removeFromWatchlist = require('../../assets/icons/removeFromWatchlist.png'),
    addToWatchlist = require('../../assets/icons/addToWatchlist.png'),
    markAsSeen = require('../../assets/icons/markAsSeen.png'),
    markAsUnseen = require('../../assets/icons/markAsUnseen.png'),
    search_unselected = require('../../assets/icons/search.png'),
    search = require('../../assets/icons/search_selected.png'),
    left = require('../../assets/icons/left.png'),
    right = require('../../assets/icons/right.png'),
    x = require('../../assets/icons/x.png'),
    review = require('../../assets/icons/review.png'),
    popcorn = require('../../assets/icons/popcorn.png'),
    percentTemplate = require('../../assets/icons/percentTemplate.png'),
    email = require('../../assets/icons/email.png'),
    account = require('../../assets/icons/account.png'),
    account_unselected = require('../../assets/icons/account_unselected.png'),
    edit = require('../../assets/icons/edit.png'),
}